### PR TITLE
Map Exports by ArmedVeteran

### PR DESCRIPTION
**Pull request by ArmedVeteran**
I've managed to export some (38, I think?) popular maps. I've added all of the required info to the README.
Chernarus Autumn, Summer and Winter all point to the same tilePattern to optimize size (since they are the same maps, I've just copied the Chernarus html and js files and changed the names everywhere except for the tilePattern).

Also, I think it would be wise to set up LFS, because those PNGs tend to have quite a size.

### CODE REVIEW

**Comment by jetelain** [comment]
Great job ! I did not excepte to have so many maps so quickly.

Just one little issue : `Chernarus_Winter` should be all lowercase.

If you have time, it would be great to add workshop link in the generated js files (`steamWorkshop` entry), I can do it by the way.

I will also regenerate the "all.js" and "all.json" files to allow cTab to be able to detect new maps once it's merged.

**Comment by ArmedVeteran** [comment]
I'll add those entries as soon as I can (tomorrow most likely). As for Chernarus_Winter - I think it should be written with first letters being capital, since this is how it looks in the config (scenarios on this map end with .Chernarus_Winter as well).

image

**Comment by jetelain** [comment]
Everything is forced lowercase in backend

**Comment by ArmedVeteran** [comment]
> Everything is forced lowercase in backend / or should be ;-)

Copy that, I'll fix it.

**Comment by jetelain** [comment]
I've published current version, it works fine on maps.plan-ops.fr.
I've made small changes on Chernarus files

**Comment by jetelain** [comment]
There is coordinates issues on somes maps, i've created an issue to track this #9

**Pull request merged**
